# Simple Linear Regression

#1 Download the file ‘insurance.csv’ from our class Blackboard site.

#2 Read this file into your R environment. Show the step that you used to accomplish this.
insurance = read.csv("insurance.csv")

#3 Filter the dataframe to create a new dataframe that only contains 
#the records of people who are not smokers.
library(dplyr)
nonsmoker = filter(insurance, smoker == 'no')

#4 Using ggplot, create a scatterplot to depict the relationship 
#between the input variable age and the output variable charges 
library(ggplot2)
ggplot(nonsmoker, aes(age, charges)) + geom_point() + geom_smooth(method = 'lm', se=FALSE)

#5 Find the correlation between age and charges. 
lm(charges~age, nonsmoker)
cor(nonsmoker$age, nonsmoker$charges, use = "complete.obs")

#6 Using your assigned seed value, create a data partition. Assign approximately 60% of
#the records to your training set, and the other 40% to your validation set. 
library(dplyr)
set.seed(150)
nonsmoker2 = sample_n(nonsmoker,1064)
training = slice(nonsmoker2, 1:640) #approximately 60.15%
validation = slice(nonsmoker2, 641:1064)

#7 Using your training set, create a simple linear regression model.
model = lm(charges~age, training)
summary(model)

#8 What is the regression equation generated by your model? Make up a hypothetical
#input value and explain what it would predict as an outcome.
inputs = data.frame(age=c(26,28,30,32,35,40,65))
round(predict(model, inputs),2)

#9 Using the accuracy() function from the forecast package, assess the accuracy of your
#model against both the training set and the validation set
library(forecast)
prediction1 = predict(model, training)
prediction2 = predict(model, validation)
accuracy(prediction1, training$charges)
accuracy(prediction2, validation$charges)
mean(nonsmoker$charges)

# Multiple Linear Regression

#1 Create a scatterplot matrix that depicts the relationships among all of the numerical
#variables that you might use as predictors (use your training set to build this).
library(GGally)
ggpairs(training[c(1,3,4)])

#2 What are Dummy Variables? (Explained in the PDF file)

#3 Create dummy variables for any categorical predictors in the data set
library(caret)
dummy1 = dummyVars("~sex", data=training, fullRank = TRUE)
dummy2 = dummyVars("~region", data=training, fullRank = TRUE)
training1 = data.frame(predict(dummy1,newdata = training))
training2 = data.frame(predict(dummy2,newdata = training))
newtraining = cbind(training,training1,training2)
View(newtraining)
dummy3 = dummyVars("~sex", data=validation, fullRank = TRUE)
dummy4 = dummyVars("~region", data=validation, fullRank = TRUE)
validation1 = data.frame(predict(dummy3,newdata = validation))
validation2 = data.frame(predict(dummy4,newdata = validation))
newvalidation = cbind(validation,validation1,validation2)
View(newvalidation)

#4 Using backward elimination, build a multiple regression model with the data in your training set
newtraining = newtraining[c(-2,-6)]
multiple = lm(charges~age+bmi+children+sex.male+region.northwest+region.southeast+
                region.southwest, data = newtraining)
summary(multiple)
multiple.step = step(multiple, direction = 'backward')

#5 Based in part on what was recommended by the backward elimination process, and in
#part on your judgement, which variables will you keep? (Explained in PDF file)

#6 Using the variables that you will keep, build a multiple linear regression model. Show
#the code you used to build it, and show a summary of your multiple regression model
multiple2 = lm(charges~age+children, data = newtraining)
summary(multiple2)

#7 Make up a fictional person, and assign this person attributes for each of the predictors
#in your model
inputs2 = data.frame(age=52, children = 3)
round(predict(multiple2, inputs2),2)
mean(nonsmoker$charges)
median(nonsmoker$charges)

#8 Using the accuracy() function from the forecast package, assess the accuracy of your
#model against both the training set and the validation set
library(forecast)
newpredict1 = predict(multiple2, training)
newpredict2 = predict(multiple2, validation)
accuracy(newpredict1, training$charges)
accuracy(newpredict2, validation$charges)



